apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: serving
  annotations:
    app.openshift.io/vcs-ref: main
    app.openshift.io/vcs-uri: https://github.com/redhat-na-ssa/demo-active-learning.git
  labels:
    app: serving
    app.kubernetes.io/component: serving
    app.kubernetes.io/instance: serving
    app.kubernetes.io/name: serving
    app.kubernetes.io/part-of: active-learning
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
