apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: labeling
  annotations:
    app.openshift.io/vcs-ref: openshift
    app.openshift.io/vcs-uri: https://github.com/redhat-na-ssa/demo-active-learning.git
  labels:
    app: labeling
    app.kubernetes.io/component: labeling
    app.kubernetes.io/instance: labeling
    app.kubernetes.io/name: labeling
    app.kubernetes.io/part-of: active-learning
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.9-ubi8
